apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: petclinic
  name: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: petclinic
    spec:
      containers:
      - image: harbor.suselabs.com/library/spring-petclinic:latest
        name: petclinic-demo
        ports:
        - containerPort: 8080
        resources: {}
---
kind: Service
apiVersion: v1
metadata:
  name: pc-service
spec:
  selector:
    app: petclinic
  ports:
  - protocol: TCP
    port: 8080
  type: NodePort